import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { federation } from '@module-federation/vite'
import path from 'path'

export default defineConfig({
  plugins: [
    react(),
    federation({
      name: 'shared',
      filename: 'remoteEntry.js',
      exposes: {
        './Button': './src/components/Button.tsx',
        './Input': './src/components/Input.tsx',
        './TextArea': './src/components/TextArea.tsx',
        './Select': './src/components/Select.tsx',
        './Checkbox': './src/components/Checkbox.tsx',
        './Modal': './src/components/Modal.tsx',
        './ConfirmDialog': './src/components/ConfirmDialog.tsx',
        './Toast': './src/components/Toast.tsx',
        './Spinner': './src/components/Spinner.tsx',
        './Skeleton': './src/components/Skeleton.tsx',
        './EmptyState': './src/components/EmptyState.tsx',
        './ErrorState': './src/components/ErrorState.tsx',
        './Dropdown': './src/components/Dropdown.tsx',
        './Table': './src/components/Table.tsx',
        './Pagination': './src/components/Pagination.tsx',
        './AuthContext': './src/contexts/AuthContext.tsx',
        './ToastContext': './src/contexts/ToastContext.tsx',
        './I18nContext': './src/contexts/I18nContext.tsx',
        './ThemeContext': './src/contexts/ThemeContext.tsx',
        './ProtectedRoute': './src/components/ProtectedRoute.tsx',
        './LanguageSwitcher': './src/components/LanguageSwitcher.tsx',
        './apiClient': './src/api/client.ts',
        './authApi': './src/services/auth.ts',
        './todoApi': './src/services/todo.ts',
        './endpoints': './src/api/endpoints.ts',
        './useDebounce': './src/hooks/useDebounce.ts',
        './useTodos': './src/hooks/useTodos.ts',
        './useTodosStats': './src/hooks/useTodosStats.ts',
        './useCreateTodo': './src/hooks/useCreateTodo.ts',
        './useUpdateTodo': './src/hooks/useUpdateTodo.ts',
        './useDeleteTodo': './src/hooks/useDeleteTodo.ts',
        './useRestoreTodo': './src/hooks/useRestoreTodo.ts',
        './useBulkDeleteTodos': './src/hooks/useBulkDeleteTodos.ts',
        './useLoginMutation': './src/hooks/useLoginMutation.ts',
        './useRegisterMutation': './src/hooks/useRegisterMutation.ts',
        './useForgotPasswordMutation': './src/hooks/useForgotPasswordMutation.ts',
        './useResetPasswordMutation': './src/hooks/useResetPasswordMutation.ts',
        './schemas': './src/schemas/index.ts',
        './types': './src/types/index.ts',
        './formatDate': './src/utils/formatDate.ts',
        './fieldError': './src/utils/fieldError.ts',
        './storage': './src/utils/storage.ts',
        './constants': './src/constants/index.ts',
        './i18n': './src/i18n',
      },
      shared: {
        react: { singleton: true },
        'react-dom': { singleton: true },
        'react-router': { singleton: true },
        axios: { singleton: true },
        'react-hook-form': { singleton: true },
        zod: { singleton: true },
        '@tanstack/react-query': { singleton: true },
        i18next: { singleton: true },
        'react-i18next': { singleton: true },
      },
      bundleAllCSS: true,
    }),
  ],
  resolve: {
    alias: { '@': path.resolve(__dirname, 'src') },
  },
  server: {
    port: 3004,
    proxy: { '/api': 'http://localhost:8080' },
  },
})
